<?php

declare(strict_types=1);

return [
    'b1te',
    'baise',
    'baiser',
    'baisé',
    'baisée',
    'baises',
    'baisez',
    'baisons',
    'batard',
    'bâtard',
    'bâtards',
    'bite',
    'bites',
    'b@tard',
    'bordel',
    'bouffon',
    'bouffonne',
    'bouffons',
    'bougnoule',
    'bougnoules',
    'cafard',
    'cafards',
    'caca',
    'chié',
    'chiée',
    'chier',
    'chies',
    'chie',
    'chiotte',
    'chiottes',
    'clito',
    'clitoris',
    'con',
    'connard',
    'connards',
    'connasse',
    'connasses',
    'conne',
    'connerie',
    'conneries',
    'cons',
    'couilles',
    'couillon',
    'couillonne',
    'crétin',
    'crétine',
    'crétins',
    'débile',
    'débiles',
    'défoncé',
    'défoncée',
    'défoncés',
    'défoncer',
    'dégueulasse',
    'dégueulasses',
    'dégueulis',
    'encule',
    'enculé',
    'enculés',
    'enculer',
    'éjaculation',
    'éjaculer',
    'éjacule',
    'fdp',
    'ferme ta gueule',
    'fils de chien',
    'fils de pute',
    'gode',
    'godemichet',
    'godemichets',
    'godes',
    'gouine',
    'gouines',
    'grognasse',
    'grognasses',
    'gros cul',
    'gros porc',
    'merde',
    'merdeuse',
    'merdeux',
    'mongol',
    'mongolien',
    'mongoliens',
    'mongols',
    'morue',
    'morues',
    'nique ta mère',
    'nique ta race',
    'ntr',
    'ntm',
    'nègre',
    'paki',
    'pakis',
    'partouze',
    'partouzes',
    'pd',
    'pédés',
    'pédé',
    'pénis',
    'pétasse',
    'pétasses',
    'pignouf',
    'pipi',
    'porc',
    'porcs',
    'put1',
    'putain',
    'puta',
    'pute',
    'pute à fric',
    'pute de luxe',
    'putes',
    'queue',
    'queues',
    'raton',
    'ratons',
    's@lope',
    'salope',
    'salopes',
    'salopard',
    'saloperie',
    'sexe',
    'sexe anal',
    'sexe oral',
    'sidaïque',
    'sidaïques',
    'sodomie',
    'sodomisé',
    'sodomiser',
    'suce',
    'suceuse',
    'suceuses',
    'sucer',
    'tafiole',
    'tafioles',
    'ta gueule',
    'tapette',
    'tapettes',
    'tapin',
    'tapineuse',
    'tapineuses',
    'tapins',
    'tarlouze',
    'tarlouzes',
    'tg',
    'travelo',
    'travelos',
    'truie',
    'truies',
    'trou de balle',
    'trou du cul',
    'trouduc',
    'turlute',
    'turluter',
    'turluttes',
    'va te faire enculer',
    'va te faire foutre',
    'vagin',
    'vtfe',
    'vtff',
    'youpin',
    'youpine',
    'youpines',
    'youpins',
    'zob',
];
