name: Static Analysis

on: ['push', 'pull_request']

jobs:
  static:
    name: Static Tests

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        tools: composer:v2
        coverage: none

    - name: Install Dependencies
      run: COMPOSER_ROOT_VERSION=dev-4.x composer update --prefer-stable --no-interaction --no-progress --ansi

    - name: Style
      run: composer test:lint
